version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::574836245203:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-FOKM2W8N61LV"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::574836245203:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1M1KBQ84KETZM"
cloudformation_execution_role = "arn:aws:iam::574836245203:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-7RMGTS6E7WTD"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-9jrwnxmumke3"
image_repository = ""
region = "eu-west-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::574836245203:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-164UJL56SN8RE"
cloudformation_execution_role = "arn:aws:iam::574836245203:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-4NSJSL2QKETH"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-guga2nqgzc06"
image_repository = ""
region = "eu-west-1"
